[catalogue]
catalogue.vkdevin.online 

[redis]
redis.vkdevin.online 

[user]
user.vkdevin.online 

[cart]
cart.vkdevin.online 

[rabbitmq]
rabbitmq.vkdevin.online 

[shipping]
shipping.vkdevin.online 

[mysql]
mysql.vkdevin.online 

[payment]
payment.vkdevin.online  

[mongodb]
mongodb.vkdevin.online 

[frontend]
vkdevin.online 

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321







