- name: mangodb by roles
  become: yes
  hosts: mongodb
  roles:     #here we use roles insteead of tasks and here roles is a directory and we created it and and also created mongodb file there  
  - mongodb   #so here we are saying go ansible goto roles and search for mongodb
              #  so tasks were stored in roles/mongodb/tasks so in that task we kept main.yaml inthat all task were there. please check
