- name: copy "{{ component }}" service
  ansible.builtin.template:                    #so here before we used copy but now we should use template because we stored catalouge.service file in template. and by templates we can easily do chnages in template only  by using variables.
    src: "{{ component }}.service.j2"      #here we should use  catalogue.service.j2  --.j2 because we are using jinja2 there and the file name also catalogue.service.j2 so.
    dest: "/etc/systemd/system/{{ component }}.service"
  tags:
    - start

- name: systemctl deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  tags:
      - start

- name: start and enable "{{ component }}"
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted  #even app in not running we can restart
    enabled: yes
  tags:
     - start


#------------------►ERROR FACED:◄-----------------------
#See above  on line 3and 4 u just need to keep double codeds starting and end of the line 
#Because for 3rd we  using jinja sooit will not take 
#for 4th very important before i given as "{{ component }} " so it saved service file in  this path /etc/systemd/system/ 
#as "user".service so it took "" also as name so i gotr error as 
##--------------►*fatal: [user.vkdevin.online]: FAILED! => {"changed": false, "msg": "Could not find the requested service user: host"}--------------
#so we should double codes start and end of the line  only when it comes to any copy or saving files so yes









     # so here we used tags  to run only systemctl.yaml so if u wated to run emntire catalogue service keeep tags as a comment or remove it 

      #So befor in "{{ component }}" in this place we used catalogue for catalogue cofiguraition soo again when we use this code for user component then we used arugument called component so we can run by giving component name simply in command line 

      #samee as app set up
