- name: appsetup 
  ansible.builtin.include_role:
    name: common   #folder name 
    tasks_from: app-setup.yaml

- name: install nodejs
  ansible.builtin.include_role:
    name: common   #folder name 
    tasks_from: nodejs.yaml

- name: configure systemctl
  ansible.builtin.include_role:
    name: common   #folder name 
    tasks_from: systemctl.yaml

    #above three are common for catalogue and user so we kept this code in common folder.